/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminProdutoRouteImport } from './routes/_authenticated/admin.produto'
import { Route as AuthenticatedAdminVendasRouteImport } from './routes/_authenticated/admin.vendas'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardCadastroRouteImport } from './routes/_authenticated/dashboard.cadastro'
import { Route as AuthenticatedDashboardComprarRouteImport } from './routes/_authenticated/dashboard.comprar'
import { Route as AuthenticatedDashboardComprasRouteImport } from './routes/_authenticated/dashboard.compras'
import { Route as ApiPublicSeedAdminRouteImport } from './routes/api/public/seed-admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProdutoRoute =
  AuthenticatedAdminProdutoRouteImport.update({
    id: '/produto',
    path: '/produto',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVendasRoute =
  AuthenticatedAdminVendasRouteImport.update({
    id: '/vendas',
    path: '/vendas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCadastroRoute =
  AuthenticatedDashboardCadastroRouteImport.update({
    id: '/cadastro',
    path: '/cadastro',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardComprarRoute =
  AuthenticatedDashboardComprarRouteImport.update({
    id: '/comprar',
    path: '/comprar',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardComprasRoute =
  AuthenticatedDashboardComprasRouteImport.update({
    id: '/compras',
    path: '/compras',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicSeedAdminRoute = ApiPublicSeedAdminRouteImport.update({
  id: '/api/public/seed-admin',
  path: '/api/public/seed-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/produto': typeof AuthenticatedAdminProdutoRoute
  '/admin/vendas': typeof AuthenticatedAdminVendasRoute
  '/dashboard/cadastro': typeof AuthenticatedDashboardCadastroRoute
  '/dashboard/comprar': typeof AuthenticatedDashboardComprarRoute
  '/dashboard/compras': typeof AuthenticatedDashboardComprasRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/produto': typeof AuthenticatedAdminProdutoRoute
  '/admin/vendas': typeof AuthenticatedAdminVendasRoute
  '/dashboard/cadastro': typeof AuthenticatedDashboardCadastroRoute
  '/dashboard/comprar': typeof AuthenticatedDashboardComprarRoute
  '/dashboard/compras': typeof AuthenticatedDashboardComprasRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/produto': typeof AuthenticatedAdminProdutoRoute
  '/_authenticated/admin/vendas': typeof AuthenticatedAdminVendasRoute
  '/_authenticated/dashboard/cadastro': typeof AuthenticatedDashboardCadastroRoute
  '/_authenticated/dashboard/comprar': typeof AuthenticatedDashboardComprarRoute
  '/_authenticated/dashboard/compras': typeof AuthenticatedDashboardComprasRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/admin/clientes'
    | '/admin/produto'
    | '/admin/vendas'
    | '/dashboard/cadastro'
    | '/dashboard/comprar'
    | '/dashboard/compras'
    | '/api/public/seed-admin'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/clientes'
    | '/admin/produto'
    | '/admin/vendas'
    | '/dashboard/cadastro'
    | '/dashboard/comprar'
    | '/dashboard/compras'
    | '/api/public/seed-admin'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/produto'
    | '/_authenticated/admin/vendas'
    | '/_authenticated/dashboard/cadastro'
    | '/_authenticated/dashboard/comprar'
    | '/_authenticated/dashboard/compras'
    | '/api/public/seed-admin'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicSeedAdminRoute: typeof ApiPublicSeedAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/produto': {
      id: '/_authenticated/admin/produto'
      path: '/produto'
      fullPath: '/admin/produto'
      preLoaderRoute: typeof AuthenticatedAdminProdutoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/vendas': {
      id: '/_authenticated/admin/vendas'
      path: '/vendas'
      fullPath: '/admin/vendas'
      preLoaderRoute: typeof AuthenticatedAdminVendasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/cadastro': {
      id: '/_authenticated/dashboard/cadastro'
      path: '/cadastro'
      fullPath: '/dashboard/cadastro'
      preLoaderRoute: typeof AuthenticatedDashboardCadastroRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/comprar': {
      id: '/_authenticated/dashboard/comprar'
      path: '/comprar'
      fullPath: '/dashboard/comprar'
      preLoaderRoute: typeof AuthenticatedDashboardComprarRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/compras': {
      id: '/_authenticated/dashboard/compras'
      path: '/compras'
      fullPath: '/dashboard/compras'
      preLoaderRoute: typeof AuthenticatedDashboardComprasRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/seed-admin': {
      id: '/api/public/seed-admin'
      path: '/api/public/seed-admin'
      fullPath: '/api/public/seed-admin'
      preLoaderRoute: typeof ApiPublicSeedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminProdutoRoute: typeof AuthenticatedAdminProdutoRoute
  AuthenticatedAdminVendasRoute: typeof AuthenticatedAdminVendasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminProdutoRoute: AuthenticatedAdminProdutoRoute,
  AuthenticatedAdminVendasRoute: AuthenticatedAdminVendasRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardCadastroRoute: typeof AuthenticatedDashboardCadastroRoute
  AuthenticatedDashboardComprarRoute: typeof AuthenticatedDashboardComprarRoute
  AuthenticatedDashboardComprasRoute: typeof AuthenticatedDashboardComprasRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardCadastroRoute: AuthenticatedDashboardCadastroRoute,
    AuthenticatedDashboardComprarRoute: AuthenticatedDashboardComprarRoute,
    AuthenticatedDashboardComprasRoute: AuthenticatedDashboardComprasRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicSeedAdminRoute: ApiPublicSeedAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
